function out1 = dyn_subject11_TIPM_FFFB_backwards(t,in2,in3)
%DYN_SUBJECT11_TIPM_FFFB_BACKWARDS
%    OUT1 = DYN_SUBJECT11_TIPM_FFFB_BACKWARDS(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Jun-2019 22:54:31

u1 = in3(1,:);
u2 = in3(2,:);
u3 = in3(3,:);
u4 = in3(4,:);
u5 = in3(5,:);
u6 = in3(6,:);
u7 = in3(7,:);
u8 = in3(8,:);
u9 = in3(9,:);
u10 = in3(10,:);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
out1 = [-x2;u5.*(-1.0./6.0e1)-(u1.*x1)./6.0e1-(u2.*x2)./6.0e1-(u3.*x3)./6.0e1-(u4.*x4)./6.0e1;-x4;u10.*(-1.0./6.0e1)-(u6.*x1)./6.0e1-(u7.*x2)./6.0e1-(u8.*x3)./6.0e1-(u9.*x4)./6.0e1+9.81e2./1.0e2];
