function out1 = dyn_subject11_TIPM_InputBounds_backwards(t,in2,in3)
%DYN_SUBJECT11_TIPM_INPUTBOUNDS_BACKWARDS
%    OUT1 = DYN_SUBJECT11_TIPM_INPUTBOUNDS_BACKWARDS(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    21-Nov-2019 14:08:18

u1 = in3(1,:);
u2 = in3(2,:);
u3 = in3(3,:);
u4 = in3(4,:);
u5 = in3(5,:);
u6 = in3(6,:);
u7 = in3(7,:);
u8 = in3(8,:);
u9 = in3(9,:);
u10 = in3(10,:);
u11 = in3(11,:);
u12 = in3(12,:);
u13 = in3(13,:);
u14 = in3(14,:);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
out1 = [-x2;u6.*(-1.0./1.2e2)-u7./1.2e2-(u2.*x1)./6.0e1-(u3.*x2)./6.0e1-(u4.*x3)./6.0e1-(u5.*x4)./6.0e1-(u1.*(u6./2.0-u7./2.0))./6.0e1;-x4;u13.*(-1.0./1.2e2)-u14./1.2e2-(u9.*x1)./6.0e1-(u10.*x2)./6.0e1-(u11.*x3)./6.0e1-(u12.*x4)./6.0e1-(u8.*(u13./2.0-u14./2.0))./6.0e1+9.81e2./1.0e2];
