function out1 = dyn_subject7_TIPM_BFFFB_backwards(t,in2,in3)
%DYN_SUBJECT7_TIPM_BFFFB_BACKWARDS
%    OUT1 = DYN_SUBJECT7_TIPM_BFFFB_BACKWARDS(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    25-Jun-2019 22:57:49

u1 = in3(1,:);
u2 = in3(2,:);
u3 = in3(3,:);
u4 = in3(4,:);
u5 = in3(5,:);
u6 = in3(6,:);
u7 = in3(7,:);
u8 = in3(8,:);
u9 = in3(9,:);
u10 = in3(10,:);
u11 = in3(11,:);
u12 = in3(12,:);
u13 = in3(13,:);
u14 = in3(14,:);
x1 = in2(1,:);
x2 = in2(2,:);
x3 = in2(3,:);
x4 = in2(4,:);
out1 = [-x2;u6.*(-5.0./5.38e2)-u7.*(5.0./5.38e2)-u2.*x1.*(5.0./2.69e2)-u3.*x2.*(5.0./2.69e2)-u4.*x3.*(5.0./2.69e2)-u5.*x4.*(5.0./2.69e2)-u1.*(u6./2.0-u7./2.0).*(5.0./2.69e2);-x4;u13.*(-5.0./5.38e2)-u14.*(5.0./5.38e2)-u9.*x1.*(5.0./2.69e2)-u10.*x2.*(5.0./2.69e2)-u11.*x3.*(5.0./2.69e2)-u12.*x4.*(5.0./2.69e2)-u8.*(u13./2.0-u14./2.0).*(5.0./2.69e2)+9.81e2./1.0e2];
